# Generated by Django 3.0.5 on 2020-04-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('desc', models.TextField(max_length=2048)),
            ],
        ),
    ]
