# Generated by Django 3.0.5 on 2020-05-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200430_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('desc', models.TextField(max_length=2048)),
                ('contactinfo', models.BigIntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MostWantedCriminals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('desc', models.TextField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateField(max_length=30)),
                ('image', models.ImageField(upload_to='pics')),
                ('desc', models.TextField(max_length=2048)),
                ('phoneno', models.BigIntegerField(max_length=10)),
                ('emailid', models.EmailField(max_length=30)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
