# Generated by Django 3.0.5 on 2020-05-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200430_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
