# Generated by Django 3.0.5 on 2020-05-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Threat',
        ),
    ]
