# Generated by Django 3.0.5 on 2020-05-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_threat'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('News_Title', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('Date', models.DateField(max_length=30)),
                ('Image', models.ImageField(blank=True, upload_to='pics')),
                ('Description', models.TextField(max_length=2048)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RenameField(
            model_name='agencies',
            old_name='desc',
            new_name='Agency_Description',
        ),
        migrations.RenameField(
            model_name='mostwantedcriminals',
            old_name='name',
            new_name='Criminal_Name',
        ),
        migrations.RenameField(
            model_name='mostwantedcriminals',
            old_name='desc',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='mostwantedcriminals',
            old_name='image',
            new_name='Image',
        ),
        migrations.RemoveField(
            model_name='agencies',
            name='contactinfo',
        ),
        migrations.RemoveField(
            model_name='agencies',
            name='image',
        ),
        migrations.RemoveField(
            model_name='agencies',
            name='name',
        ),
        migrations.AddField(
            model_name='agencies',
            name='Agency_Address',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencies',
            name='Agency_Name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencies',
            name='Contact_Info',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencies',
            name='Image',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
